### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by npscience** [open-data-day-cambridge-2018/open-data-day-cambridge-2018.github.io#13]
Places we've targeted

- [x] personal networks
- [x] codebar cambridge
- [ ] Women in tech communities on twitter (@DjangoGirls @WWCLondon @DevelopHerUK @girl_geeks)

@yochannah other places you suggest we push? I'm going to do some comms tonight.

**Comment by yochannah** [comment]
I've shared it in the RSE UK slack group. I'm wracking my brains for other places to share and will add if they come up!

**Comment by yochannah** [comment]
- [ ] OpenConCam mailing list?

**Comment by npscience** [comment]
Good shout. Are you on that? If so, would you mind doing it? Bit of a conflict right now as we're in final push for promoting eLife Sprint, so don't want to confuse anyone with lots of emails from me.

**Comment by yochannah** [comment]
Yup, will do
