### ISSUE TITLE
Theme / scope

### ISSUE THREAD

**Issue by npscience** [open-data-day-cambridge-2018/open-data-day-cambridge-2018.github.io#2]
What is the day for?

- [x] simple one sentence
- [x] explain in a paragraph

**Comment by yochannah** [comment]
These are both present on https://open-data-day-cambridge-2018.github.io/ - if changes are needed, edit index.md

![image](https://user-images.githubusercontent.com/9271438/36354439-59eb8876-14cc-11e8-9765-1e2622201d64.png)
