### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by npscience** [open-data-day-cambridge-2018/open-data-day-cambridge-2018.github.io#3]
- [x] what will we do and when?
- [ ] important things to include
- [x] timings

**Comment by npscience** [comment]
On timings, I suggest 10-4:30ish to give 5. 5 hours work, 1.5 hour in breaks

**Comment by yochannah** [comment]
https://github.com/open-data-day-cambridge-2018/open-data-day-cambridge-2018/blob/master/schedule.md tentative schedule, open to adjustments and arguments. 

For the intro do we want to present anything? Perhaps ideas like possible datasources to draw from or sharing ideas amongst us about what we would like to work on to help find teams?

**Comment by yochannah** [comment]
I think this is all present in [schedule.md](schedule.md) unless we you have anything to add? Re-open issue if needed
