### ISSUE TITLE
Inviting people

### ISSUE THREAD

**Issue by npscience** [open-data-day-cambridge-2018/open-data-day-cambridge-2018.github.io#4]
- [ ] who?
- [ ] how?
- [ ] by when?

**Comment by npscience** [comment]
By when? I would suggest we close a sign-up sheet by the day before.

I have little preference over the how.

And many things that I think we agree on for the who - very keen to be welcoming to people who want to learn

**Comment by yochannah** [comment]
We have up to £150 diversity budget to help people who might not otherwise be able to come.

**Comment by yochannah** [comment]
Sign-up: https://www.eventbrite.co.uk/e/open-data-day-cambridge-2018-tickets-43277756936

- has 20 spaces. We'll presumably want to take two ourselves.

who: if we're both suffering from not-having-much-time the fastest option might be an open call on twitter ;) plus personal invites to anyone we'd specifically like to come.

**Comment by npscience** [comment]
Fabulous, thank you. I've added myself.

Let's invite specific people this week, then put out an open call on Saturday - I can do this saturday AM on twitter, if you'd like to do the same?

**Comment by yochannah** [comment]
Perfect, will do

**Comment by npscience** [comment]
ODD suggests a strong theme for the event. May I suggest we target people who want to learn something new, and particularly URMs? i.e. our USP is as a friendly study space?

I can drop the invite out to the codebar group in Cambridge.

**Comment by yochannah** [comment]
Open call sent out & the registration page is now open! I've tried to go for the "come and have fun exploring data" angle.

**Comment by npscience** [comment]
Perfect, thank you!
