### ISSUE TITLE
Catering

### ISSUE THREAD

**Issue by npscience** [open-data-day-cambridge-2018/open-data-day-cambridge-2018.github.io#5]
- [x] lunch
- [x] snacks
- [x] drinks
- [x] paper plates

We have cutlery, glasses, mugs in the office. But not many plates at all.

**Comment by npscience** [comment]
What's the budget here? What's your preference on food?

**Comment by yochannah** [comment]
Budget is up to £200 total - estimating ~10/head for up to 20 people. 

### menu options
#### Sandwich trays
Within that budget we could probably get finger foods for snacks, and 3-4 trays of sandwiches. I think a platter of sandwiches is around ~[£22 from Subway](https://www.subwayfresh2u.co.uk/plattersshowcase.aspx) if that's tolerable. Do we know of any other caterers we like? 

#### Bread and dips
Alternatively, crudites, nice bread, hummus and dips, salad, olives could be a self-assembled option but it would take more time. Thoughts? This option is more work and might be less filling?


###  Dietary requirements
I'm veggie so will make sure that angle's covered. We'll need to check if anyone might have other requirements like gluten free though. 

### drinks
If possible, drinks needs to include cold drinks (perhaps juice to go along with meals) as well as tea/coffee.

**Comment by npscience** [comment]
I think a sandwich option is good. We now use orgin8 https://www.origin8delicafes.com/lunch/SetLunches?product_id=41

6.30/head and pretty good - sandwiches, crisps, cakes, fruit
Plus we can buy juice and drinks in from tesco/coop down the road.
That should be plenty and take the least work?

If you agree, I can give them a ring. We probably want to do that by Tuesday 27th (once we have a better idea of numbers).

Unless you need to pay for it via your account? Happy to do so myself if that works for your grant.

**Comment by yochannah** [comment]
I'll double check and get back to you!

**Comment by yochannah** [comment]
Is one option for the caterers to invoice the SSI, do you know? If so, that's probably easier. And I think it is ok if you pay for things, too, but I'm still waiting for word from the SSI (my fault mostly, not theirs!)

~One important stipulation: We need to make sure there's vegan food (for me, if no one else!) If the caterer can't do this I can arrange separately.~ (Edit: I can see there is hummus + tomato. Brilliant.)

**Comment by npscience** [comment]
I’ll ask them tomorrow and let you know

**Comment by npscience** [comment]
-- forgot today, sorry. Will give them call tomorrow!

**Comment by yochannah** [comment]
If they can't invoice the SSI, paying them and claiming the money back should work ok too.

**Comment by npscience** [comment]
Origin8 are already booked for Saturday.

I'm happy to arrange alternatives; any objections to the following:
- [ ] Subway (easy and nearby)
- [ ] Limoncello ~£10pp (we could order for 15, would be plenty) + £10 delivery https://cdn.shopify.com/s/files/1/1977/0781/files/Limoncello_catering.compressed_502b9f2d-622f-4642-ab37-2b39a5466939.pdf?7521908461962307530 
- [ ] others?

**Comment by yochannah** [comment]
Either looks fine, so long as something veganey is available - removing cheese from some of (but not all, too many people would find that boring!) the vegetarian limoncello options would work, for example.

**Comment by npscience** [comment]
Ok, I'll book tomorrow. May stick to subway (although how do they do vegan??), then get in some interesting juice/snacks, etc from Tesco.

**Comment by npscience** [comment]
Lunch ordered from Cambridge Blue, TBC.
Provided at eLife already: coffee, tea, squash, water; plus mugs and some plates.

I'll bring paper plates and buy some juice and snacks on the way in.
