### ISSUE TITLE
Use opendataday.org resources

### ISSUE THREAD

**Issue by yochannah** [open-data-day-cambridge-2018/open-data-day-cambridge-2018.github.io#6]
http://opendataday.org/

- [x]  register the event on the site
- [x] they have a logo generator! 
- [x] http://opendataday.org/#resources has nice data sources we can pull from

**Comment by npscience** [comment]
I've registered us on ODD site, using the github.io site, so we can add a link to the Eventbrite registration there when we're ready.

**Comment by npscience** [comment]
Can we close this now?
